rmdir /S /Q Debug
rmdir /S /Q ipch
rmdir /S /Q Release
del /F /S /A:H Basics.*.suo

del /F /S Basics.sdf

rmdir /S /Q Test_1\Debug
rmdir /S /Q Test_1\Release

rmdir /S /Q Test_2\Debug
rmdir /S /Q Test_2\Release

rmdir /S /Q Test_3\Debug
rmdir /S /Q Test_3\Release

rmdir /S /Q Test_4\Debug
rmdir /S /Q Test_4\Release

rmdir /S /Q Test_5\Debug
rmdir /S /Q Test_5\Release

rmdir /S /Q Test_6\Debug
rmdir /S /Q Test_6\Release

rmdir /S /Q Test_7\Debug
rmdir /S /Q Test_7\Release

rmdir /S /Q Test_8\Debug
rmdir /S /Q Test_8\Release

rmdir /S /Q Test_9\Debug
rmdir /S /Q Test_9\Release

rmdir /S /Q Test_10\Debug
rmdir /S /Q Test_10\Release
